[package]
name = "android-sparse"
version = "0.3.1"
authors = ["Jan Teske <jan.teske@gmail.com>"]
description = "An implementation of Android's sparse file format."
repository = "https://gitlab.com/haellowyyn/android-sparse-rs"
readme = "README.md"
keywords = ["android", "sparse"]
categories = ["command-line-utilities", "compression", "parsing"]
license = "MIT/Apache-2.0"

[dependencies]
byteorder = "1"
clap = "2"
crc = "1"

[badges]
gitlab = { repository = "haellowyyn/android-sparse-rs" }
