[package]
name = "android-sparse"
version = "0.4.0"
authors = ["Jan Teske <jteske@posteo.net>"]
description = "An implementation of Android's sparse file format."
repository = "https://gitlab.com/ra_kete/android-sparse-rs"
readme = "README.md"
keywords = ["android", "sparse"]
categories = ["command-line-utilities", "compression", "parsing"]
license = "MIT"

[dependencies]
byteorder = "1"
clap = "2"
crc = "1"

[dev-dependencies]
tempfile = "3"

[badges]
gitlab = { repository = "ra_kete/android-sparse-rs" }
